package com.warrenpostma;

import com.bitwig.extension.api.util.midi.ShortMidiMessage;
import com.bitwig.extension.callback.ShortMidiMessageReceivedCallback;
import com.bitwig.extension.controller.api.ControllerHost;
import com.bitwig.extension.controller.api.Transport;
import com.bitwig.extension.controller.ControllerExtension;


import com.warrenpostma.util.ConsoleLogger;

import java.io.Console;

/* generated by bitwig
 *    bitwigstarterExtension
 *
 */
public class bitwigstarterExtension extends ControllerExtension
{
   protected bitwigstarterExtension(final bitwigstarterExtensionDefinition definition, final ControllerHost host)
   {
      super(definition, host);

      ConsoleLogger.init(host);
   }

   public void showPopupNotification( final String msg)
   {
      final ControllerHost host = getHost();
      host.showPopupNotification(msg);
      //System.out.printf("%s\n",msg);
      final String msgFormat = String.format("showPopupNotification: %s",msg);
      ConsoleLogger.log(msgFormat);


   }

   @Override
   public void init()
   {
      final ControllerHost host = getHost();      

      mTransport = host.createTransport();
      host.getMidiInPort(0).setMidiCallback((ShortMidiMessageReceivedCallback)msg -> onMidi0(msg));
      host.getMidiInPort(0).setSysexCallback((String data) -> onSysex0(data));

      // TODO: Perform your driver initialization here.
      // For now just show a popup notification for verification that it is running.
      showPopupNotification("bitwigstarter Initialized");
   }

   @Override
   public void exit()
   {
      // TODO: Perform any cleanup once the driver exits
      // For now just show a popup notification for verification that it is no longer running.
      getHost().showPopupNotification("bitwigstarter Exited");
   }

   @Override
   public void flush()
   {
      // TODO Send any updates you need here.
   }

   /** Called when we receive short MIDI message on port 0. */
   private void onMidi0(ShortMidiMessage msg) 
   {
      final String msgLog = String.format("midi: channel=%d   data1=%d, data2=%d ",msg.getChannel(), msg.getData1(), msg.getData2() );
      ConsoleLogger.log(msgLog);

      // TODO: Implement your MIDI input handling code here.
   }

   /** Called when we receive sysex MIDI message on port 0. */
   private void onSysex0(final String data) 
   {
      final String msgLog = String.format("SYSEX %s ",data );
      ConsoleLogger.log(msgLog);


      // MMC Transport Controls:
      if (data.equals("f07f7f0605f7"))
            mTransport.rewind();
      else if (data.equals("f07f7f0604f7"))
            mTransport.fastForward();
      else if (data.equals("f07f7f0601f7"))
            mTransport.stop();
      else if (data.equals("f07f7f0602f7"))
            mTransport.play();
      else if (data.equals("f07f7f0606f7"))
            mTransport.record();
   }

   private Transport mTransport;
}
